apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-chi-deployment
  labels:
    app: majha-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: majha-nginx
  template:
    metadata:
      labels:
        app: majha-nginx
    spec:
      containers:
      - name: nginx-cha-container
        image: nginx:latest
        env:
#        - name: ENVIRONMENT
#          value: "production"
#        - name: LOG_LEVEL
#          value: "info"
          - name: ENVIRONMENT
            valueFrom:
                configMapKeyRef:
                  name: nginx-config
                  key: APP_ENV
          - name: LOG_LEVEL
            valueFrom:
                configMapKeyRef:
                  name: nginx-config
                  key: LOG_LEVEL
          - name: DB_USERNAME
            valueFrom:
                secretKeyRef:
                  name: nginx-secret
                  key: DB_USERNAME
          - name: DB_PASSWORD
            valueFrom:
                secretKeyRef:
                  name: nginx-secret
                  key: DB_PASSWORD
          - name: SECRET_KEY
            valueFrom:
                secretKeyRef:
                  name: nginx-secret
                  key: SECRET_KEY
        ports:
        - containerPort: 80

#      it is 80 beacuse nginx by default listens on port 80 and we are exposing that port in the service
#      as well, targetport and nodeport are for routing the traffic to the correct port on the container and
#      the node respectively.
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service-majhi
spec:
  selector:
    app: majha-nginx
  ports:
  - protocol: TCP
    port: 8182
    targetPort: 80
    nodePort: 30080
  type: NodePort